-- Ten additional Vortex Precision IT catalog products.
-- Safe to run once in cPanel → phpMyAdmin → SQL; SKU checks prevent duplicates.

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Globe Valve VP-GV-300','vortexpro-globe-valve-vp-gv-300','VP-VLV-GV300','A forged-steel globe valve for precise throttling and isolation in steam, condensate and high-temperature process lines. The bolted bonnet, graphite packing and hard-faced trim support dependable maintenance intervals.','Forged-steel globe valve for controlled steam and process service.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'power-generation' LIMIT 1),(SELECT id FROM industries WHERE slug = 'oil-gas' LIMIT 1)),'ASTM A105 / 13Cr trim','Class 300','-29 to 425 °C','N/A','1/2 in to 8 in','18 kg',JSON_ARRAY('ASME B16.34','API 623','API 598'),'IN_STOCK',0,1,0,'VortexPro Globe Valve VP-GV-300','Forged-steel globe valve for controlled steam and process service.' FROM categories c WHERE c.slug='valves' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-VLV-GV300');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Butterfly Valve VP-BF-150','vortexpro-butterfly-valve-vp-bf-150','VP-VLV-BF150','A resilient-seated butterfly valve with a wafer body and ISO 5211 actuator pad. Designed for compact shutoff on water, utility and low-pressure process systems.','Resilient-seated wafer butterfly valve for utility and water service.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'water-wastewater' LIMIT 1),(SELECT id FROM industries WHERE slug = 'food-beverage' LIMIT 1)),'Ductile iron body / EPDM seat','PN16 / Class 150','-10 to 120 °C','N/A','2 in to 24 in','12 kg',JSON_ARRAY('API 609','ISO 5211','EN 593'),'IN_STOCK',0,1,0,'VortexPro Butterfly Valve VP-BF-150','Compact resilient-seated butterfly valve for utility and water systems.' FROM categories c WHERE c.slug='valves' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-VLV-BF150');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro API Process Pump VP-AP-610','vortexpro-api-process-pump-vp-ap-610','VP-PMP-AP610','A centerline-mounted process pump engineered for refinery and chemical duties. The heavy-duty bearing frame, API seal chamber and back-pull-out construction simplify planned service.','API 610 process pump for refinery and chemical plant duties.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'oil-gas' LIMIT 1),(SELECT id FROM industries WHERE slug = 'chemical-processing' LIMIT 1)),'Carbon steel casing / 316 stainless wetted parts','25 bar','-40 to 400 °C','400 / 460 V 3ph','3x2x13 in','410 kg',JSON_ARRAY('API 610','API 682','ISO 5199'),'MADE_TO_ORDER',1,1,0,'VortexPro API Process Pump VP-AP-610','Centerline-mounted API process pump for demanding hydrocarbon service.' FROM categories c WHERE c.slug='pumps' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-PMP-AP610');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Vertical Turbine Pump VP-VT-90','vortexpro-vertical-turbine-pump-vp-vt-90','VP-PMP-VT90','A multistage vertical turbine pump for raw-water intake, cooling-water and municipal lift applications. Bowl assemblies are configured to match required flow, head and installation depth.','Multistage vertical turbine pump for water intake and lift stations.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'water-wastewater' LIMIT 1),(SELECT id FROM industries WHERE slug = 'power-generation' LIMIT 1)),'Cast iron / 316 stainless options','16 bar','0 to 85 °C','400 / 460 V 3ph','Up to 18 m bowl assembly','680 kg',JSON_ARRAY('API 610','AWWA E101'),'MADE_TO_ORDER',0,1,0,'VortexPro Vertical Turbine Pump VP-VT-90','Configured vertical turbine pump for water intake and cooling-water service.' FROM categories c WHERE c.slug='pumps' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-PMP-VT90');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Shell & Tube Exchanger VP-ST-500','vortexpro-shell-tube-exchanger-vp-st-500','VP-HX-ST500','A TEMA-style shell-and-tube heat exchanger with removable bundle, thermal expansion allowance and configurable tube metallurgy. Built for reliable heat recovery, cooling and condensing duties.','TEMA-style shell-and-tube exchanger with removable bundle.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'oil-gas' LIMIT 1),(SELECT id FROM industries WHERE slug = 'chemical-processing' LIMIT 1)),'Carbon steel shell / 316L tube bundle','30 bar shell / 20 bar tube','-40 to 400 °C','N/A','Up to 1200 mm shell diameter','1,850 kg',JSON_ARRAY('ASME Section VIII','TEMA','PED 2014/68/EU'),'MADE_TO_ORDER',1,1,0,'VortexPro Shell & Tube Exchanger VP-ST-500','Custom TEMA shell-and-tube exchanger for heat recovery and process cooling.' FROM categories c WHERE c.slug='heat-exchangers' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-HX-ST500');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Brazed Plate Exchanger VP-BP-40','vortexpro-brazed-plate-exchanger-vp-bp-40','VP-HX-BP40','A compact copper-brazed plate heat exchanger that provides high thermal efficiency in a small footprint. Suitable for hydraulic oil cooling, heat-pump loops and secondary glycol circuits.','Compact brazed plate exchanger for hydraulic and glycol circuits.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'food-beverage' LIMIT 1),(SELECT id FROM industries WHERE slug = 'water-wastewater' LIMIT 1)),'316 stainless steel / copper braze','30 bar','-196 to 225 °C','N/A','120 to 300 mm plate pack','8 kg',JSON_ARRAY('PED 2014/68/EU','UL'),'IN_STOCK',0,1,0,'VortexPro Brazed Plate Exchanger VP-BP-40','High-efficiency compact plate heat exchanger for hydraulic and glycol duty.' FROM categories c WHERE c.slug='heat-exchangers' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-HX-BP40');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Filter Separator VP-FS-800','vortexpro-filter-separator-vp-fs-800','VP-FLT-FS800','A two-stage filter separator for removing particulates and free water from hydrocarbon streams. Replaceable elements and a quick-opening closure reduce turnaround time.','Two-stage hydrocarbon filter separator with quick-opening closure.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'oil-gas' LIMIT 1),(SELECT id FROM industries WHERE slug = 'chemical-processing' LIMIT 1)),'Carbon steel / stainless internals','20 bar','-20 to 120 °C','N/A','800 mm diameter','940 kg',JSON_ARRAY('ASME Section VIII','API 1581'),'MADE_TO_ORDER',0,1,0,'VortexPro Filter Separator VP-FS-800','Two-stage filter separator for particulate and free-water removal.' FROM categories c WHERE c.slug='filtration' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-FLT-FS800');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Self-Cleaning Filter VP-SC-100','vortexpro-self-cleaning-filter-vp-sc-100','VP-FLT-SC100','An automatic self-cleaning screen filter that protects pumps, membranes and nozzles without frequent manual intervention. Differential-pressure control initiates the flush cycle.','Automatic self-cleaning screen filter for continuous water treatment.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'water-wastewater' LIMIT 1),(SELECT id FROM industries WHERE slug = 'food-beverage' LIMIT 1)),'316L stainless steel','10 bar','5 to 80 °C','230 / 400 V','DN50 to DN200','95 kg',JSON_ARRAY('CE','NSF/ANSI 61 option'),'IN_STOCK',0,1,0,'VortexPro Self-Cleaning Filter VP-SC-100','Automatic screen filter for continuous water and process protection.' FROM categories c WHERE c.slug='filtration' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-FLT-SC100');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Coriolis Flowmeter VP-CF-25','vortexpro-coriolis-flowmeter-vp-cf-25','VP-INS-CF25','A precision Coriolis mass flowmeter providing mass flow, density and temperature measurements for batching, custody transfer and process control. Local display and digital communications are included.','Coriolis mass flowmeter for precision batching and process measurement.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'chemical-processing' LIMIT 1),(SELECT id FROM industries WHERE slug = 'pharmaceutical' LIMIT 1)),'316L stainless measuring tubes','100 bar','-50 to 180 °C','24 VDC','DN15 to DN80','22 kg',JSON_ARRAY('MID','OIML R117','3-A option'),'MADE_TO_ORDER',1,1,0,'VortexPro Coriolis Flowmeter VP-CF-25','Precision Coriolis meter for mass flow, density and batching control.' FROM categories c WHERE c.slug='instrumentation' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-INS-CF25');

INSERT INTO products (id,name,slug,sku,description,shortDescription,categoryId,industryIds,material,pressure,temperature,voltage,dimensions,weight,certifications,availability,featured,isActive,views,metaTitle,metaDescription)
SELECT UUID(),'VortexPro Smart Pressure Transmitter VP-PT-400','vortexpro-smart-pressure-transmitter-vp-pt-400','VP-INS-PT400','A smart pressure transmitter with 4–20 mA HART output, local configuration buttons and remote seal options. It delivers stable pressure measurement for hazardous and general process areas.','Smart HART pressure transmitter for reliable process measurement.',c.id,JSON_ARRAY((SELECT id FROM industries WHERE slug = 'oil-gas' LIMIT 1),(SELECT id FROM industries WHERE slug = 'power-generation' LIMIT 1)),'316L stainless steel','Up to 600 bar','-40 to 125 °C','10.5 to 42 VDC','1/2 in NPT process connection','1.4 kg',JSON_ARRAY('ATEX','IECEx','SIL 2'),'IN_STOCK',0,1,0,'VortexPro Smart Pressure Transmitter VP-PT-400','Smart HART transmitter for hazardous and general process areas.' FROM categories c WHERE c.slug='instrumentation' AND NOT EXISTS (SELECT 1 FROM products WHERE sku='VP-INS-PT400');
